### PR TITLE
updating web-animations dependency to latest, and bumping to 1.0.9

### PR DESCRIPTION
**Pull request by tjsavage**

### CODE REVIEW

**Comment by tjsavage** [comment]
go home googlebot you're drunk

**Comment by tjsavage** [comment]
@notwaldorf would you mind taking a quick look? This is just to update to the latest web-animation release: https://github.com/web-animations/web-animations-js/releases/tag/2.1.4

**Comment by notwaldorf** [comment]
Let's pink @azakus to get some Travis tests in here first, since this looks scary to merge otherwise :)

**Comment by notwaldorf** [comment]
@tjsavage seems to be borked on edge. maybe open a bug about it? otherwise lgtm

**Comment by tjsavage** [comment]
It looks like this test was broken on edge before this PR as well. Let's do some cleanup before bringing this in.

**Comment by ianlet** [comment]
@notwaldorf @tjsavage I noticed the test was broken on Edge a few weeks ago with the previous continuous integration tool. It was broken on the master branch. I wanted to have a look at the bug but I didn't have acces to an Edge browser at that time.

**Comment by addyosmani** [comment]
The original bump currently requires some rebasing against master. @tjsavage will you have a chance to take a look at whether the issues with Edge are in a better state now? If not, happy to.

**Comment by tjsavage** [comment]
closing in favor of https://github.com/PolymerElements/neon-animation/pull/136

**Pull request closed without merging**
