### PR TITLE
Move paper-styles to devDependencies

### LINKED ISSUE #110: Move paper-styles to devDependencies
I think it's only used under demos so no need for every user to download. Right?

### PR DESCRIPTION
**Pull request by mikaelharsjo**
This fixes #110 by moving paper-styles to devDependencies.

### CODE REVIEW

**Comment by cdata** [comment]
Thanks for the contribution! It looks like the branch is out of date. Can you rebase?

**Comment by mikaelharsjo** [comment]
Not really following this anymore. Probably faster if you do a new PR?

**Comment by cdata** [comment]
Will do, thanks anyway.

**Comment by ebidel** [comment]
Closing this then :)

**Pull request closed without merging**
