### PR TITLE
fix stuck squelchEvent flag

### PR DESCRIPTION
**Pull request by atotic**
This fixes https://github.com/PolymerElements/neon-animation/issues/74 and #71

### CODE REVIEW

**Comment by semateos** [comment]
This fix works for me...

**Comment by hawkett** [comment]
Is there anything preventing this from being merged?

**Comment by cdata** [comment]
LGTM :+1: Thanks for the fix, @atotic !

**Comment by hawkett** [comment]
This is probably a fix for #46, #71 and maybe #81 (although @atotic raised  81 so perhaps not).

**Pull request merged**
