### PR TITLE
Bower: dont lock in web-animations-js version

### PR DESCRIPTION
**Pull request by ebidel**
R: all, @addyosmani

### CODE REVIEW

**Comment by samuelli** [comment]
Thanks; merged fix in https://github.com/PolymerElements/neon-animation/pull/163

**Comment by ebidel** [comment]
Can we release a new version so the io site can pick up this change?

**Comment by samuelli** [comment]
Yup, I'll do so today (in a few hours), just looking at fixing the build and seeing if there's anything else that can be pushed quickly. That ok?

**Comment by ebidel** [comment]
SGTM. LMK

**Comment by samuelli** [comment]
@ebidel FYI, released.

**Pull request closed without merging**
