### PR TITLE
Add deprecation notice to neon-animation

### PR DESCRIPTION
**Pull request by aomarks**

### CODE REVIEW

**Comment by dman777** [comment]
I thought neon elements were deprecated in Polymer 2.0. I see there is a 3.0 release... are neon elements no longer deprecated?

**Comment by aomarks** [comment]
They are still deprecated, but we did make a 3.0 so that users could migrate to modules independently of migrating away from neon-animation.

**Comment by dman777** [comment]
Ok, thank you. I don't know why but the deprecation notice does not show on webcomponents.org or in npm

**Comment by aomarks** [comment]
> Ok, thank you. I don't know why but the deprecation notice does not show on webcomponents.org or in npm

That's because the README file is read out of NPM, not GitHub, so since this PR which added the notice, we'll need to publish a new version in order for it to be updated.

**Pull request merged**
